name: dash

services:
  dash:
    build:
      context: .
    ports:
      - 8585:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PROJECT: dash
    labels:
      dev.orbstack.domains: dash.local
