name: dash

services:
  dash:
    build:
      context: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PROJECT: ${COMPOSE_PROJECT_NAME}
    labels:
      dev.orbstack.domains: dash.local
